stages:
  prepare:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw
    - src/data/make_dataset.py
    outs:
    - data/processed/split
  standardize:
    cmd: python src/data/standardize.py
    deps:
    - data/processed/split
    - src/data/standardize.py
    outs:
    - data/processed/standardized
  grid_search:
    cmd: python src/models/grid_search.py
    deps:
    - data/processed/standardized
    - src/models/grid_search.py
    outs:
    - models/params
  train:
    cmd: python src/models/train_model.py
    deps:
    - models/params
    - src/models/train_model.py
    outs:
    - models/model
  evaluate:
    cmd: python src/models/predict.py
    deps:
    - models/model
    - src/models/predict.py
    outs:
    - metrics
